---
# handlers file for kubenodes_conf
- name: restart docker service
  service:
    name: docker
    state: restarted

- name: load /etc/sysctl.d/k8s.conf
  command: sysctl -p /etc/sysctl.d/k8s.conf

- name: load /etc/sysctl.d/88-hugepages.conf
  command: sysctl -p /etc/sysctl.d/88-hugepages.conf

- name: restart ssh service
  service:
    name: ssh
    state: restarted

- name: ntpdate sync time now
  command: "ntpdate {{ ntpdate_server }}"

- name: restart systemd-resolved service
  service:
    name: systemd-resolved
    state: restarted