---

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /tmp/k8s_join_cmd.sh
    state: absent

- name: push local k8s_join_cmd.json to target host
  ansible.builtin.copy:
    src: ./tmp/k8s_join_cmd.sh
    dest: /tmp/k8s_join_cmd.sh
    owner: root
    group: root
    mode: '0755'
    backup: yes

- name: "Performs a best effort revert of changes made to this host by 'kubeadm init' or 'kubeadm join'"
  command:
    cmd: "kubeadm reset --force"

# k8s_master_join_cmd like this:
# kubeadm join k8s.cluster.local:6443 --token mdjtnj.ewrwatcff3tluml2 --discovery-token-ca-cert-hash sha256:00545ed6985a015f84cd9b878e6dc21f24683501b0379cefd2909647cfe7cfe4 --control-plane --certificate-key af8f391c0c4d849710539766514a9627039951e2d2793df92e7a68985e307051

# https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
- name: new worker join to cluster test
  command: sh /tmp/k8s_join_cmd.sh
