---
- name: Get cluster nodes names and join command
  hosts: first_master
  tasks:
    - include_role:
        name: get_cluster_node_names

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: ./tmp/k8s_join_cmd.sh
        state: absent

    - name: get the cluster join cmd from master
      shell: |
        kubeadm token create --print-join-command > /tmp/k8s_join_cmd.sh
      
    - name: save cmd to local tmp/k8s_join_cmd.sh
      synchronize:
        mode: pull
        src: /tmp/k8s_join_cmd.sh
        dest: ./tmp/k8s_join_cmd.sh

- name: Add other master to cluster
  hosts: other_master
  tasks:
    - include_role:
        name: add_other_master

- name: Add other workers to cluster
  hosts: worker
  tasks:
    - include_role:
        name: add_worker